<<<<<<< HEAD
import { Header } from '@/components/header'
import './globals.css'
import type { Metadata } from 'next'
import { Saira } from 'next/font/google'

const saira = Saira({ 
  weight: ['300', '400', '500', '600'],
  subsets: ['latin'] 
})
=======
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
>>>>>>> refs/remotes/origin/master

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={saira.className}>
        <Header />
        {children}
      </body>
=======
      <body className={inter.className}>{children}</body>
>>>>>>> refs/remotes/origin/master
    </html>
  )
}
